
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PURCHASE_STATE = "UPDATE_PURCHASE_STATE";
export const FETCHED_INGREDIENT_FALIED ="FETCHED_INGREDIENT_FALIED";
export const SET_INGREDIENT = "SET_INGREDIENT"
export const INIT_INGREDIENT = "INIT_INGREDIENT"

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const purchaseBurgerStart = "purchaseBurgerStart"
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"
export const showLoadingHandler = "showLoadingHandler"
export const PURCHASED_ORDER = "PURCHASED_ORDER"

export const FETCH_ORDER_START = "FETCH_ORDER_START" 
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS" 
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED" 
export const FETCH_ORDER  = "FETCH_ORDER"
export const FETCH_ORDER_INIT = "FETCH_ORDER_INIT"

export const FETCH_ORDER_DELETE ="FETCH_ORDER_DELETE"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH"
export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT"
export const AUTH_CHECK_EXPIRATION_TIME = "AUTH_CHECK_EXPIRATION_TIME"
export const AUTH_USER ="AUTH_USER"

export const AUTH_CHECK_STATE ="AUTH_CHECK_STATE"